TTHKgamejam2023/Models/ErrorViewModel.cs
namespace TTHKgamejam2023.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TTHKgamejam2023/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using TTHKgamejam2023.Models;

namespace TTHKgamejam2023.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Contacts()
        {
            return View();
        }
        public IActionResult GameJam2023()
        {
            return View();
        }
        public IActionResult ItchIo()
        {
            return View();
        }
        public IActionResult Voting()
        {
            return View();
        }
        public IActionResult Results()
        {
            return View();
        }
        public IActionResult SecretPage()
        {
            return View();
        }
        public IActionResult Projects2023()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TTHKgamejam2023/Controllers/ShowcaseController.cs
using Microsoft.AspNetCore.Mvc;

namespace TTHKgamejam2023.Controllers
{
    public class ShowcaseController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

TTHKgamejam2023/Views/Home/Contacts.cshtml
@{
    ViewData["Title"] = "Kontaktid";
}
<h1>@ViewData["Title"]</h1>

<p>
    Kontaktid:<br />
    <br />
    Kutseõpetaja - jyri.vaitmaa@tthk.ee<br />
    Huvijuht - lilian.kold@tthk.ee<br />
</p>

TTHKgamejam2023/Views/Home/GameJam2023.cshtml
@{
    ViewData["Title"] = "Game Jam 2023";
}
<div class="text-center">
    <h4>TTHK Sügisene Game Jam 2023</h4>
    <h1 class="display-4">Vahtraleht ja kõrvits</h1>
    <img src="~/images/leeftransAMEDIUM.png" alt="transparent pixel leaf A" />
    <img src="~/images/pompkentransMEDIUM.png" alt="transparent pixel pumpkin" />
    <img src="~/images/leeftransBMEDIUM.png" alt="transparent pixel leaf B" />
    <br />
</div>

<h2><img src="~/images/leeftransA.png" alt="transparent pixel leaf A" /> Game Jam Teema? <img src="~/images/leeftransB.png" alt="transparent pixel leaf B" /> </h2>
<p class="text-start">
    <img src="~/images/pompkentrans.png" alt="transparent pixel pumpkin" /> Igal korralikul Game Jamil on oma teema, ja nii ka seegi kord. Esimese Game Jami teemaks on kõrvits ja vahtralehed. <br />
    Tere tulemast sügisesesse maagiasse meie Game Jam'is! Sel korral võtame vastu väljakutse, kus kõrvitsad ja vahtrad moodustavad meie
    inspiratsioonirikkad teljed. Kujutle end metsades jalutamas, kui kõrvitsad valmivad päikese käes ja vahtrad sahistavad tuules. See on meie loominguline fookuspunkt, mis paneb meid mõtlema sügisestele päevadele, kuldsetele lehtedele
    ja soojust kiirgavatele kõrvitsapirukatele.<br />

    Ootame, et jagaksid oma unikaalseid mõtteid sellest hooajalisest looduse ilust lähtuvalt. Olgu su mängus kõrvitsatest loodud seiklusmaailm või vahtrapuude varjus peituv saladus, las see teema inspireerib sind looma midagi erakordset. Mõtle säravatele sügiskarvadele, krõbisevatele lehtedele ja mängulistele kõrvitsanägudele – kõik on võimalik!<br />

    Liitu meiega sel põneval Game Jam'il, kus sügiseloodus saab meie virtuaalse mängumaailma osaks. Ole osa sellest loovast seiklusest ja anna oma panus mängumaailma sügisesse võlusse!
</p>
<br />
<br />
<br />
<h2><img src="~/images/leeftransA.png" alt="transparent pixel leaf A" /> Reeglid? <img src="~/images/leeftransB.png" alt="transparent pixel leaf B" /> </h2>
<p class="text-start">
    <img src="~/images/pompkentrans.png" alt="transparent pixel pumpkin" />
    Korralikul Game Jam'il on ka kahjuks (loe: "õnneks") reeglid. Alljärgnev on nimekiri reeglitest <br /><br />
    <b>Kes võib osaleda?</b><br />
    Osaleda võivad kõik TTHK õpilased ja õpetajad, erialast olenemata! Ole sa kas noorem tarkvaraarendaja või juuksur,
    kui oskad siis tule ja tee midagi lahedat! <br /><br />
    <b>Mida ma selle jaoks kasutada võin?</b><br />
    Mängu loomisel võid kasutada kõike mis ise arvad sobib sinu projekti jaoks. Vahet pole kas tööriistaks on Unity, 
    Game Maker, RenPy, PyGame, Godot või midagi muud millega ise tuttav ning osav oled!<br /><br />
    <b>Kuidas see mäng välja nägema peab?</b><br />
    Et mäng kvalifitseeruks vastuvõetavaks, on vaja ära kasutada ainult etteantud teemat, kuidas ja mis kujul seda kasutada on sinu enda välja mõelda ning teha!<br /><br />
    <b>Kus ma seda mängu tegema pean?</b><br />
    Kodus, kohvikus, koolis vahetunnis, raamatukogus - kus mugavam on! Ametlikult pole Game Jam'i jaoks asukohta koolil spetsiifiliselt ette nähtud. Ehk teisisõnu, toimub Game Jam pilves/distantsilt itch.io ja Google keskkondades <br /><br />
    <b>Kui peale teema on antud enam-vähem vabad käed, kas on midagi mida teha ei tohi?</b><br />
    Jah, olemasolevat mängu maha teha ei tohi. Näiteks olemasoleva mängu ringihäkkimine ja siis selle mängu esitamine oma nime alt. Antud Game Jam on siiski orienteeritud originaalsusele, sestap ei ole ka eksisteerivate mängude modimised lubatud.<br /><br />
    <b>Ok, kas on midagi peale teema mida mu mäng igal juhul sisaldama peaks?</b><br />
    Jah, paar asja siiski on, mida iga mäng peab sisaldama. Nendeks on: <br />
    <ul>
        <li>Avaekraani kooli logoga</li>
        <li>Avaekraani mis kirjeldab ära kes mängu tegid, ning et mäng on tehtud selle Game Jami jaoks</li>
    </ul>
    <b>Kui mäng on valmis, kuhu ma selle saadan?</b><br />
    Vaata menüüst "Itch.Io Info" lehele. Seal on link mis viib õige Game Jami juurde.<br /><br />
    <b>Kuna seda aega teha on?</b><br />
    Ajakava Game Jami jaoks on allpool!<br /><br />
    <b>Kas mäng jääb koolile?</b><br />
    Ei! Kõik õigused sinu tööle jäävad sulle, kool ei võta Game Jamis osalemise eest mitte midagi, ega jäta endale mitte midagi. Rahalist osalust kellelgi ei ole ja mitte keegi ei kaota õigusi oma mängule.<br /><br />
    <b>Mäng on tehtud ja üles laetud, mis nüüd?</b><br />
    Peale mängude tegemisperioodi toimub hääletusperiood! hääleta oma lemmiku poolt seitsmes kategoorias:<br />
    <ul>
        <li>Ilusaim Graafika</li>
        <li>Huvitavaim Gameplay</li>
        <li>Põnevaim Story</li>
        <li>Parim Heli</li>
        <li>Top Shelf Memes (naljakaim lahendus)</li>
        <li>Kõige Potensiaalikaim</li>
        <li>Kõige parem üleüldine mäng</li>
    </ul>

</p>
<br />
<br />
<br />
<h2><img src="~/images/leeftransA.png" alt="transparent pixel leaf A" /> Ajakava? <img src="~/images/leeftransB.png" alt="transparent pixel leaf B" /> </h2>
<p class="text-start">
    <img src="~/images/pompkentrans.png" alt="transparent pixel pumpkin" />
    Game Jami ajakava on järgmine: <br /><br />
    <b>Mängude tegemine:</b><br />
    Mängude tegemise ja itch.io lehele üleslaadimise aeg algab 30 Oktoober ning lõppeb 5. november. <br /><br />
    <b>Mängude hääletamine:</b><br />
   Hääletuse ajavahemik on 7-10 november, pane tähele sellele saidile, üles ilmub õigel ajal link hääletusele.<br /><br />
    <b>Tulemuste avalikustamine:</b><br />
    Tulemused avalikustatakse 13. novembril<br /><br />
</p>
<br />
<br />
<br />

TTHKgamejam2023/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h4>TTHK Sügisgamejam 2023</h4>
    <h1 class="display-4">Vahtraleht ja kõrvits</h1>
    <br />
    <p>
        <h2>Tere tulemast TTHK 2023 aasta sügisesele Game Jamile!</h2><br />
        <img src="~/images/leeftransAMEDIUM.png" alt="transparent pixel leaf A" />
        <img src="~/images/pompkentransMEDIUM.png" alt="transparent pixel pumpkin" />
        <img src="~/images/leeftransBMEDIUM.png" alt="transparent pixel leaf B" />
    </p>

</div>
<div class="text-center">
    <p>
        Game Jam on selleks korraks läbi! Vaata tulemusi <a asp-action="Results">Siit</a>.
    </p>
</div>
<div class="text-center">
    <p>
        Tere tulemast TTHK esimesse Game Jam'i! Oleme põnevil kutsuda kõiki mänguhuvilisi osalema selles TTHK jaoks <br/>
        esmakordes sündmuses, kus looming ja lõbu saavad kokku. Mõtle väljaspool kasti ja lase oma ideedel voolata,<br />
        sest esimese TTHK Game Jam'i teemaks on kõrvitsad ja vahtralehed. Kujutle, kuidas saad nende sügiseselt <br />
        võluvatel elementidel põhinevate mängude kaudu tuua esile oma loovuse ja programmeerimisoskused. See on <br />
        suurepärane võimalus ühendada jõud oma klassikaaslastega või siis näidata välja oma soolojõud ning arendada <br />
        üks sügiseselt atmosfäärikas ja huvitav mäng. Ootame sind - Hakkaja TTHK õpilane - et koos kujundada mänguelamusi,<br />
        mis toovad esile sügiskuude soojust ja värvikust. Tule ja ühine meiega sellel seiklusrohkel Game Jam'il, kus loome koos mänge, mis jäävad meelde!
    </p>
</div>
<br />
<br />
<div >
    <p class ="text-start">
        Reegleid ja muud infot loe <a asp-action="GameJam2023">Siit</a>
    </p>
</div>

TTHKgamejam2023/Views/Home/ItchIo.cshtml
@{
    ViewData["Title"] = "Itch.Io Info";
    DateTime itchiorelease = new DateTime(2023, 10, 29,23,59,59);
}
@*@if (DateTime.Now < itchiorelease)
{
    <div class="text-danger">
        <p>Link lehele kuvatakse @itchiorelease.Date kuupäeval</p>
        @Html.Partial("_NotAvailable")
    </div>
}
@if (DateTime.Now >= itchiorelease)
{*@
    <div class="text-center">
        <h4>TTHK Sügisene Game Jam 2023</h4>
        <h1 class="display-4">Itch.Io Info</h1>
        <img src="~/images/leeftransAMEDIUM.png" alt="transparent pixel leaf A" />
        <img src="~/images/pompkentransMEDIUM.png" alt="transparent pixel pumpkin" />
        <img src="~/images/leeftransBMEDIUM.png" alt="transparent pixel leaf B" />
        <br />
    </div>

    <h2><img src="~/images/leeftransA.png" alt="transparent pixel leaf A" />Mis on Itch.Io? <img src="~/images/leeftransB.png" alt="transparent pixel leaf B" /> </h2>
    <p class="text-start">
        <img src="~/images/pompkentrans.png" alt="transparent pixel pumpkin" /> Itch.io on digitaalne platvorm mis on loodud eesmärgiga anda kunstnikele, mänguarendajatele ja loovisikutele võimalus oma loomingut esitleda ja jagada ilma suurte piiranguteta. Platvormil saab luua projekte erinevates žanrites, sealhulgas mänge, interaktiivseid kogemusi, graafilisi romaane, muusikat, e-raamatuid ja palju muud.
        <br />
        <br />

        Itch.io pakub arendajatele paindlikkust oma toodete hinnastamisel, sealhulgas võimalust pakkuda oma loomingut tasuta või lasta kasutajatel ise määrata hinna vastavalt nende eelarvele ja väärtushinnangutele. See teeb platvormist atraktiivse keskkonna nii professionaalsetele mänguarendajatele kui ka algajatele, kes soovivad oma projekte maailmaga jagada.
        <br />
        <br />

        Lisaks on Itch.io tuntud oma avatud ja kogukonnakeskse lähenemise poolest. See võimaldab kasutajatel hinnata, kommenteerida ja jagada lemmikteoseid ning toetada otse arendajaid nende loomingu eest tasumise kaudu. Itch.io on seega mitmekesine platvorm, mis soodustab loomingulist mitmekesisust ja kogukonnaühendust.
    </p>
    <br />
    <br />
    <br />
    <h2><img src="~/images/leeftransA.png" alt="transparent pixel leaf A" />Mis on Itch.Iol pistmist TTHK Game Jam'iga? <img src="~/images/leeftransB.png" alt="transparent pixel leaf B" /> </h2>
    <p class="text-start">
        <img src="~/images/pompkentrans.png" alt="transparent pixel pumpkin" />
        Game Jam kasutab Itch.Io keskkonna Game Jam'ide loomisvõimalusi, seega on vajalik, et iga osavõtjal kas juba on seal kasutaja, või loob sinna oma kasutaja. Kuidas seda teha, palun vaadake <a href="https://www.itch.io">Itch.Io</a> Kodulehelt.

    </p>
    <br />
    <br />
    <br />
    <h2><img src="~/images/leeftransA.png" alt="transparent pixel leaf A" /> Miks peab mänge kuskile mujale üles laadima? <img src="~/images/leeftransB.png" alt="transparent pixel leaf B" /> </h2>
    <p class="text-start">
        <img src="~/images/pompkentrans.png" alt="transparent pixel pumpkin" />
        Kasutame Itch.Io keskkonda kuna Itch.iol on juba funktsioneeriv ja omadusterikas Game Jam'i teostamiseks sihipärane ja sobiv platvorm olemas. See hoidis kokku suure hulga tööd mida muidu meil endil teha oleks tulnud. Ei ole mõtet hakata ratast uuesti leiutama.
        Itch.Iosse mängude üleslaadimine, ning Game Jam'i sisestamine on tehtud suhteliselt lihtsaks, ning kui mäng laadida itch.iosse üles on ka osalejad teinud kas esimese sammu või järjekordse sammu arvutimängude loomise maailmas, kuna Itch.io mitte ainult ei võõrusta loojate mänge, vaid on ka otseselt koht kus loojad otse oma loomingut maailmale kuvada saavad, tasuta kusjuures.
    </p>
    <br />
    <br />
    <br />
    <h2><img src="~/images/leeftransA.png" alt="transparent pixel leaf A" />Ok, kuidas ma Itch.io lehelt selle õige Jami üles leian? <img src="~/images/leeftransB.png" alt="transparent pixel leaf B" /> </h2>
    <p class="text-start">
        <img src="~/images/pompkentrans.png" alt="transparent pixel pumpkin" />
        Vajutades sellele nupule:
        <br />
        <a href="https://itch.io/jam/383735/preview" class="btn btn-primary">TTHK Game Jam 2023</a>
    </p>
    <br />
    <br />
    <br />
    <h4><img src="~/images/leeftransA.png" alt="transparent pixel leaf A" />Head Arendamist! <img src="~/images/leeftransB.png" alt="transparent pixel leaf B" /> </h4>
    <br />
    <br />
    <br />
@*}*@

TTHKgamejam2023/Views/Home/Projects2023.cshtml
@{
    ViewData["Title"] = "2023 mängud";
    DateTime resultrelease = new DateTime(2023, 11, 13);
}
@*@if (DateTime.Now < resultrelease)
{
    <div class="text-danger">
        <p>Link lehele kuvatakse @resultrelease.Date kuupäeval</p>
        @Html.Partial("_NotAvailable")
    </div>
}
@if (DateTime.Now >= resultrelease)
{*@
<div class="text-center">
    <h4>TTHK Sügisene Game Jam 2023</h4>
    <h1 class="display-4">2023 Mängud</h1>
    <img src="~/images/leeftransAMEDIUM.png" alt="transparent pixel leaf A" />
    <img src="~/images/pompkentransMEDIUM.png" alt="transparent pixel pumpkin" />
    <img src="~/images/leeftransBMEDIUM.png" alt="transparent pixel leaf B" />
    <br />
</div>

<h2><img src="~/images/leeftransA.png" alt="transparent pixel leaf A" /> 2023 Mängud <img src="~/images/leeftransB.png" alt="transparent pixel leaf B" /> </h2>
<p class="text-start">
    <img src="~/images/pompkentrans.png" alt="transparent pixel pumpkin" /> 2023 Sügisese Game Jam'i raames tehtud projektid:
    <br />
    <table class="table">
        <thead>
        <th>Mängu nimi</th>
        <th>Autor(id)</th>
        <th>Pilt</th>
        <th>Link</th>
        <th>Žanr</th>
        <th>Rühm</th>
        <th></th>
        </thead>
        <tbody>
            <tr>
                <td>Super Pumpkin</td>
                <td><a href="https://makud3v.itch.io/">makud3v</a></td>
                <td><img src="https://img.itch.zone/aW1hZ2UvMjM1MTk1Mi8xMzkzMTk2MC5wbmc=/original/avLovb.png" height="232" /> </td>
                <td> <a href="https://makud3v.itch.io/super-pumpkin" class="btn btn-primary">Mängi</a></td>
                <td>Platformer</td>
                <td>TARpe22</td>
            </tr>
        </tbody>
    </table>
</p>
<br />
<br />
<br />
@*}*@

TTHKgamejam2023/Views/Home/Results.cshtml
@{
    ViewData["Title"] = "Tulemused";
    DateTime resultrelease = new DateTime(2023, 11, 13);
}
@*@if (DateTime.Now < resultrelease)
{
    <div class="text-danger">
        <p>Link lehele kuvatakse @resultrelease.Date kuupäeval</p>
        @Html.Partial("_NotAvailable")
    </div>
}
@if (DateTime.Now >= resultrelease)
{*@
    <div class="text-center">
        <h4>TTHK Sügisene Game Jam 2023</h4>
        <h1 class="display-4">Tulemused</h1>
        <img src="~/images/leeftransAMEDIUM.png" alt="transparent pixel leaf A" />
        <img src="~/images/pompkentransMEDIUM.png" alt="transparent pixel pumpkin" />
        <img src="~/images/leeftransBMEDIUM.png" alt="transparent pixel leaf B" />
        <br />
    </div>

    <h2><img src="~/images/leeftransA.png" alt="transparent pixel leaf A" />Game Jami parima tulemuse saavutanud Projektid <img src="~/images/leeftransB.png" alt="transparent pixel leaf B" /> </h2>
    <p class="text-start">
        <br />
        <table class="table">
            <thead>
            <th>Saavutatud Koht</th>
            <th>Mängu nimi</th>
            <th>Autor(id)</th>
            <th>Pilt</th>
            <th>Link</th>
            <th>Žanr</th>
            <th>Rühm</th>
            <th></th>
            </thead>
            <tbody>
                <tr>
                <td>Esimene koht<br /><img src="~/images/pompkentrophy1sttrans.png" alt="transparent pixel pumpkin trophy for first place" /></td>
                    <td>Super Pumpkin</td>
                    <td><a href="https://makud3v.itch.io/">makud3v</a></td>
                    <td><img src="https://img.itch.zone/aW1hZ2UvMjM1MTk1Mi8xMzkzMTk2MC5wbmc=/original/avLovb.png" height="232" /> </td>
                    <td> <a href="https://makud3v.itch.io/super-pumpkin" class="btn btn-primary">Mängi</a></td>
                    <td>Platformer</td>
                    <td>TARpe22</td>
                </tr>
            </tbody>
        </table>
        <br />
    </p>
    <br />
    <br />
    <br />
@*}*@

TTHKgamejam2023/Views/Home/SecretPage.cshtml
<div class="text-center">
    <h4>TTHK Sügisene Game Jam 2023</h4>
    <h1 class="display-4">Secret Page!</h1>
    <br />
</div>

<p class="text-start">
    <img src="~/images/leeftransA.png" alt="transparent pixel leaf A 1" />
    <img src="~/images/pompkentrans.png" alt="transparent pixel pumpkin 1" />
    <img src="~/images/leeftransB.png" alt="transparent pixel leaf B 1" />
    <br />
    <img src="~/images/leeftransAMEDIUM.png" alt="transparent pixel leaf A 2" />
    <img src="~/images/pompkentransMEDIUM.png" alt="transparent pixel pumpkin 2" />
    <img src="~/images/leeftransBMEDIUM.png" alt="transparent pixel leaf B 2" />
    <br />
    <img src="~/images/leeftransABIG.png" alt="transparent pixel leaf A 3" />
    <img src="~/images/pompkentransBIG.png" alt="transparent pixel pumpkin 3" />
    <img src="~/images/leeftransBBIG.png" alt="transparent pixel leaf B 3" />
    <br />
    <img src="~/images/leeftransALARGE.png" alt="transparent pixel leaf A 4" />
    <img src="~/images/pompkentransLARGE.png" alt="transparent pixel pumpkin 4" />
    <img src="~/images/leeftransBLARGE.png" alt="transparent pixel leaf B 4" />
</p>

TTHKgamejam2023/Views/Home/Voting.cshtml
@{
    ViewData["Title"] = "Itch.Io Info";
    DateTime votingrelease = new DateTime(2023, 11, 07);
}
@*@if (DateTime.Now < votingrelease)
{
    <div class="text-danger">
        <p>Link lehele kuvatakse @votingrelease.Date kuupäeval</p>
        @Html.Partial("_NotAvailable")
    </div>
}
@if (DateTime.Now >= votingrelease)
{*@
    <div class="text-center">
        <h4>TTHK Sügisene Game Jam 2023</h4>
        <h1 class="display-4">Hääletamine</h1>
        <img src="~/images/leeftransAMEDIUM.png" alt="transparent pixel leaf A" />
        <img src="~/images/pompkentransMEDIUM.png" alt="transparent pixel pumpkin" />
        <img src="~/images/leeftransBMEDIUM.png" alt="transparent pixel leaf B" />
        <br />
    </div>

    <h2><img src="~/images/leeftransA.png" alt="transparent pixel leaf A" />Kuidas Hääletada? <img src="~/images/leeftransB.png" alt="transparent pixel leaf B" /> </h2>
    <p class="text-start">
    <img src="~/images/pompkentrans.png" alt="transparent pixel pumpkin" />Hääletamine toimub Itch.io keskkonnas, Hääletada saab iga Game Jami sisestatud mängu poolt mängu enda lehel.
    <br />
    Hääletamine algab pärast seda, kui mängude sisestusaeg on läbi. Hääletamiseks palun suundu Game Jami Itch.Io lehele.
        <br />
        <br />
    <a href="https://itch.io/jam/383735/preview" class="btn btn-primary">TTHK Game Jam 2023</a>
    </p>
    <br />
    <br />
    <br />
@*}*@

TTHKgamejam2023/Views/Shared/_Layout.cshtml
@{
    bool debugenable = true;
    DateTime itchio = new DateTime(2023, 10, 29,23,59,59);
    DateTime votingstart = new DateTime(2023, 11, 07);
    DateTime votingend = new DateTime(2023, 11, 11);
    DateTime resultreveal = new DateTime(2023, 11, 13);
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TTHK Game Jam 2023</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TTHKgamejam2023.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/images/tthktransparent.png" alt="TTHK letter only logo with transparency" width="100" /></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Esileht</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="GameJam2023">Game Jam 2023</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Showcase" asp-action="Index">TTHK Showcase</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Contacts">Contacts</a>
                        </li>
@*                        @if (DateTime.Now.Date >= itchio || debugenable == true)
                        {*@
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="ItchIo">Itch.Io Info</a>
                            </li>
@*                        }*@
                        @if (DateTime.Now.Date >= votingstart || debugenable == true)
                        {
                            if (DateTime.Now.Date <= votingend || debugenable == true)
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Voting">Hääletamine</a>
                                </li>
                            }
                        }
                        @if (DateTime.Now.Date >= resultreveal || debugenable == true)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Results">Tulemused</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Projects2023">2023 mängud</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - TTHK - <a asp-area="" asp-controller="Home" asp-action="Contacts">Contacts</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>